device_id: xcvp1202
processor:
    psv_cortexa72_0:
        arch: aarch64
        ip_name: psv_cortexa72
        slaves_strings: gic_a72 gic_its cci lpd_dma_chan0 lpd_dma_chan1 lpd_dma_chan2 lpd_dma_chan3 lpd_dma_chan4 lpd_dma_chan5 lpd_dma_chan6 lpd_dma_chan7 gem0 gpio1 i2c0 i2c1 rtc sdhci1 serial0 smmu qspi sysmon0 usb0 dwc3_0 dma0 dma1 ipi0 ipi1 ipi2 ipi3 ipi4 ipi5 ipi6 coresight versal_cips_0_pspmc_0_psv_apu_0 versal_cips_0_pspmc_0_psv_coresight_a720_cti versal_cips_0_pspmc_0_psv_coresight_a720_dbg versal_cips_0_pspmc_0_psv_coresight_a720_etm versal_cips_0_pspmc_0_psv_coresight_a720_pmu versal_cips_0_pspmc_0_psv_coresight_a721_cti versal_cips_0_pspmc_0_psv_coresight_a721_dbg versal_cips_0_pspmc_0_psv_coresight_a721_etm versal_cips_0_pspmc_0_psv_coresight_a721_pmu versal_cips_0_pspmc_0_psv_coresight_apu_cti versal_cips_0_pspmc_0_psv_coresight_apu_ela versal_cips_0_pspmc_0_psv_coresight_apu_etf versal_cips_0_pspmc_0_psv_coresight_apu_fun versal_cips_0_pspmc_0_psv_coresight_cpm_atm versal_cips_0_pspmc_0_psv_coresight_cpm_cti2a versal_cips_0_pspmc_0_psv_coresight_cpm_cti2d versal_cips_0_pspmc_0_psv_coresight_cpm_ela2a versal_cips_0_pspmc_0_psv_coresight_cpm_ela2b versal_cips_0_pspmc_0_psv_coresight_cpm_ela2c versal_cips_0_pspmc_0_psv_coresight_cpm_ela2d versal_cips_0_pspmc_0_psv_coresight_cpm_fun versal_cips_0_pspmc_0_psv_coresight_cpm_rom versal_cips_0_pspmc_0_psv_coresight_fpd_atm versal_cips_0_pspmc_0_psv_coresight_fpd_stm versal_cips_0_pspmc_0_psv_coresight_lpd_atm versal_cips_0_pspmc_0_psv_cpm versal_cips_0_pspmc_0_psv_crf_0 versal_cips_0_pspmc_0_psv_crl_0 versal_cips_0_pspmc_0_psv_crp_0 versal_cips_0_pspmc_0_psv_fpd_afi_0 versal_cips_0_pspmc_0_psv_fpd_afi_2 versal_cips_0_pspmc_0_psv_fpd_cci_0 versal_cips_0_pspmc_0_psv_fpd_gpv_0 versal_cips_0_pspmc_0_psv_fpd_slcr_0 versal_cips_0_pspmc_0_psv_fpd_slcr_secure_0 versal_cips_0_pspmc_0_psv_fpd_smmu_0 versal_cips_0_pspmc_0_psv_lpd_afi_0 versal_cips_0_pspmc_0_psv_lpd_iou_secure_slcr_0 versal_cips_0_pspmc_0_psv_lpd_iou_slcr_0 versal_cips_0_pspmc_0_psv_lpd_slcr_0 versal_cips_0_pspmc_0_psv_lpd_slcr_secure_0 versal_cips_0_pspmc_0_psv_ocm_ctrl versal_cips_0_pspmc_0_psv_pmc_aes versal_cips_0_pspmc_0_psv_pmc_bbram_ctrl versal_cips_0_pspmc_0_psv_pmc_cfi_cframe_0 versal_cips_0_pspmc_0_psv_pmc_cfu_apb_0 versal_cips_0_pspmc_0_psv_pmc_efuse_cache versal_cips_0_pspmc_0_psv_pmc_efuse_ctrl versal_cips_0_pspmc_0_psv_pmc_global_0 versal_cips_0_pspmc_0_psv_pmc_ppu1_mdm_0 versal_cips_0_pspmc_0_psv_pmc_ram_npi versal_cips_0_pspmc_0_psv_pmc_rsa versal_cips_0_pspmc_0_psv_pmc_sha versal_cips_0_pspmc_0_psv_pmc_slave_boot versal_cips_0_pspmc_0_psv_pmc_slave_boot_stream versal_cips_0_pspmc_0_psv_pmc_trng versal_cips_0_pspmc_0_psv_psm_global_reg versal_cips_0_pspmc_0_psv_rpu_0 versal_cips_0_pspmc_0_psv_scntr_0 versal_cips_0_pspmc_0_psv_scntrs_0 psv_r5_0_atcm_global psv_r5_1_atcm_global psv_r5_1_btcm_global lpd_xppu pmc_xppu pmc_xppu_npi fpd_xmpu pmc_xmpu ocm_xmpu axi_gpio_gt_ctl axi_gpio_rx_datapath axi_gpio_tx_datapath axi_reset_done_dyn axi_resets_dyn dataflow_0_axi_mcdma_0 dcmac_and_gt_dcmac_0_core
        slaves:
            axi_noc_DDR_LOW_0:
                device_type: memory
                ip_name: axi_noc_DDR_LOW
                baseaddr: '0x0'
                highaddr: '0x80000000'
            axi_noc_DDR_LOW_1:
                device_type: memory
                ip_name: axi_noc_DDR_LOW
                baseaddr: '0x800000000'
                highaddr: '0x980000000'
            psv_ocm_0:
                device_type: memory
                ip_name: psv_ocm
                baseaddr: '0xfffc0000'
                highaddr: '0x100000000'
            serial0:
                device_type: serial
                ip_name: psv_sbsauart
                baseaddr: '0xff000000'
            gem0:
                device_type: ethernet
                ip_name: psv_ethernet
            sdhci1:
                device_type: sd
                ip_name: psv_pmc_sd
            qspi:
                device_type: flash
                ip_name: psv_pmc_qspi
            gic_a72:
                ip_name: psv_acpu_gic
            cci:
                ip_name: psv_fpd_maincci
            lpd_dma_chan0:
                ip_name: psv_adma
            lpd_dma_chan1:
                ip_name: psv_adma
            lpd_dma_chan2:
                ip_name: psv_adma
            lpd_dma_chan3:
                ip_name: psv_adma
            lpd_dma_chan4:
                ip_name: psv_adma
            lpd_dma_chan5:
                ip_name: psv_adma
            lpd_dma_chan6:
                ip_name: psv_adma
            lpd_dma_chan7:
                ip_name: psv_adma
            gpio1:
                ip_name: psv_pmc_gpio
            i2c0:
                ip_name: psv_i2c
            i2c1:
                ip_name: psv_i2c
            rtc:
                ip_name: psv_pmc_rtc
            smmu:
                ip_name: psv_fpd_smmutcu
            sysmon0:
                ip_name: psv_pmc_sysmon
            usb0:
                ip_name: psv_usb
            dwc3_0:
                ip_name: psv_usb_xhci
            dma0:
                ip_name: psv_pmc_dma
            dma1:
                ip_name: psv_pmc_dma
            ipi0:
                ip_name: psv_ipi
            ipi1:
                ip_name: psv_ipi
            ipi2:
                ip_name: psv_ipi
            ipi3:
                ip_name: psv_ipi
            ipi4:
                ip_name: psv_ipi
            ipi5:
                ip_name: psv_ipi
            ipi6:
                ip_name: psv_ipi
            coresight:
                ip_name: psv_coresight
            versal_cips_0_pspmc_0_psv_apu_0:
                ip_name: psv_apu
            versal_cips_0_pspmc_0_psv_coresight_a720_cti:
                ip_name: psv_coresight_a720_cti
            versal_cips_0_pspmc_0_psv_coresight_a720_dbg:
                ip_name: psv_coresight_a720_dbg
            versal_cips_0_pspmc_0_psv_coresight_a720_etm:
                ip_name: psv_coresight_a720_etm
            versal_cips_0_pspmc_0_psv_coresight_a720_pmu:
                ip_name: psv_coresight_a720_pmu
            versal_cips_0_pspmc_0_psv_coresight_a721_cti:
                ip_name: psv_coresight_a721_cti
            versal_cips_0_pspmc_0_psv_coresight_a721_dbg:
                ip_name: psv_coresight_a721_dbg
            versal_cips_0_pspmc_0_psv_coresight_a721_etm:
                ip_name: psv_coresight_a721_etm
            versal_cips_0_pspmc_0_psv_coresight_a721_pmu:
                ip_name: psv_coresight_a721_pmu
            versal_cips_0_pspmc_0_psv_coresight_apu_cti:
                ip_name: psv_coresight_apu_cti
            versal_cips_0_pspmc_0_psv_coresight_apu_ela:
                ip_name: psv_coresight_apu_ela
            versal_cips_0_pspmc_0_psv_coresight_apu_etf:
                ip_name: psv_coresight_apu_etf
            versal_cips_0_pspmc_0_psv_coresight_apu_fun:
                ip_name: psv_coresight_apu_fun
            versal_cips_0_pspmc_0_psv_coresight_cpm_atm:
                ip_name: psv_coresight_cpm_atm
            versal_cips_0_pspmc_0_psv_coresight_cpm_cti2a:
                ip_name: psv_coresight_cpm_cti2a
            versal_cips_0_pspmc_0_psv_coresight_cpm_cti2d:
                ip_name: psv_coresight_cpm_cti2d
            versal_cips_0_pspmc_0_psv_coresight_cpm_ela2a:
                ip_name: psv_coresight_cpm_ela2a
            versal_cips_0_pspmc_0_psv_coresight_cpm_ela2b:
                ip_name: psv_coresight_cpm_ela2b
            versal_cips_0_pspmc_0_psv_coresight_cpm_ela2c:
                ip_name: psv_coresight_cpm_ela2c
            versal_cips_0_pspmc_0_psv_coresight_cpm_ela2d:
                ip_name: psv_coresight_cpm_ela2d
            versal_cips_0_pspmc_0_psv_coresight_cpm_fun:
                ip_name: psv_coresight_cpm_fun
            versal_cips_0_pspmc_0_psv_coresight_cpm_rom:
                ip_name: psv_coresight_cpm_rom
            versal_cips_0_pspmc_0_psv_coresight_fpd_atm:
                ip_name: psv_coresight_fpd_atm
            versal_cips_0_pspmc_0_psv_coresight_fpd_stm:
                ip_name: psv_coresight_fpd_stm
            versal_cips_0_pspmc_0_psv_coresight_lpd_atm:
                ip_name: psv_coresight_lpd_atm
            versal_cips_0_pspmc_0_psv_cpm:
                ip_name: psv_cpm
            versal_cips_0_pspmc_0_psv_crf_0:
                ip_name: psv_crf
            versal_cips_0_pspmc_0_psv_crl_0:
                ip_name: psv_crl
            versal_cips_0_pspmc_0_psv_crp_0:
                ip_name: psv_crp
            versal_cips_0_pspmc_0_psv_fpd_afi_0:
                ip_name: psv_fpd_afi
            versal_cips_0_pspmc_0_psv_fpd_afi_2:
                ip_name: psv_fpd_afi
            versal_cips_0_pspmc_0_psv_fpd_cci_0:
                ip_name: psv_fpd_cci
            versal_cips_0_pspmc_0_psv_fpd_gpv_0:
                ip_name: psv_fpd_gpv
            versal_cips_0_pspmc_0_psv_fpd_slcr_0:
                ip_name: psv_fpd_slcr
            versal_cips_0_pspmc_0_psv_fpd_slcr_secure_0:
                ip_name: psv_fpd_slcr_secure
            versal_cips_0_pspmc_0_psv_fpd_smmu_0:
                ip_name: psv_fpd_smmu
            versal_cips_0_pspmc_0_psv_lpd_afi_0:
                ip_name: psv_lpd_afi
            versal_cips_0_pspmc_0_psv_lpd_iou_secure_slcr_0:
                ip_name: psv_lpd_iou_secure_slcr
            versal_cips_0_pspmc_0_psv_lpd_iou_slcr_0:
                ip_name: psv_lpd_iou_slcr
            versal_cips_0_pspmc_0_psv_lpd_slcr_0:
                ip_name: psv_lpd_slcr
            versal_cips_0_pspmc_0_psv_lpd_slcr_secure_0:
                ip_name: psv_lpd_slcr_secure
            versal_cips_0_pspmc_0_psv_ocm_ctrl:
                ip_name: psv_ocm
            versal_cips_0_pspmc_0_psv_pmc_aes:
                ip_name: psv_pmc_aes
            versal_cips_0_pspmc_0_psv_pmc_bbram_ctrl:
                ip_name: psv_pmc_bbram_ctrl
            versal_cips_0_pspmc_0_psv_pmc_cfi_cframe_0:
                ip_name: psv_pmc_cfi_cframe
            versal_cips_0_pspmc_0_psv_pmc_cfu_apb_0:
                ip_name: psv_pmc_cfu_apb
            versal_cips_0_pspmc_0_psv_pmc_efuse_cache:
                ip_name: psv_pmc_efuse_cache
            versal_cips_0_pspmc_0_psv_pmc_efuse_ctrl:
                ip_name: psv_pmc_efuse_ctrl
            versal_cips_0_pspmc_0_psv_pmc_global_0:
                ip_name: psv_pmc_global
            versal_cips_0_pspmc_0_psv_pmc_ppu1_mdm_0:
                ip_name: psv_pmc_ppu1_mdm
            versal_cips_0_pspmc_0_psv_pmc_ram_npi:
                ip_name: psv_pmc_ram_npi
            versal_cips_0_pspmc_0_psv_pmc_rsa:
                ip_name: psv_pmc_rsa
            versal_cips_0_pspmc_0_psv_pmc_sha:
                ip_name: psv_pmc_sha
            versal_cips_0_pspmc_0_psv_pmc_slave_boot:
                ip_name: psv_pmc_slave_boot
            versal_cips_0_pspmc_0_psv_pmc_slave_boot_stream:
                ip_name: psv_pmc_slave_boot_stream
            versal_cips_0_pspmc_0_psv_pmc_trng:
                ip_name: psv_pmc_trng
            versal_cips_0_pspmc_0_psv_psm_global_reg:
                ip_name: psv_psm_global_reg
            versal_cips_0_pspmc_0_psv_rpu_0:
                ip_name: psv_rpu
            versal_cips_0_pspmc_0_psv_scntr_0:
                ip_name: psv_scntr
            versal_cips_0_pspmc_0_psv_scntrs_0:
                ip_name: psv_scntrs
            psv_r5_0_atcm_global:
                ip_name: psv_tcm_global
            psv_r5_1_atcm_global:
                ip_name: psv_tcm_global
            psv_r5_1_btcm_global:
                ip_name: psv_tcm_global
            lpd_xppu:
                ip_name: psv_lpd_xppu
            pmc_xppu:
                ip_name: psv_pmc_xppu
            pmc_xppu_npi:
                ip_name: psv_pmc_xppu_npi
            fpd_xmpu:
                ip_name: psv_fpd_slave_xmpu
            pmc_xmpu:
                ip_name: psv_pmc_xmpu
            ocm_xmpu:
                ip_name: psv_ocm_xmpu
            axi_gpio_gt_ctl:
                ip_name: axi_gpio
            axi_gpio_rx_datapath:
                ip_name: axi_gpio
            axi_gpio_tx_datapath:
                ip_name: axi_gpio
            axi_reset_done_dyn:
                ip_name: axi_gpio
            axi_resets_dyn:
                ip_name: axi_gpio
            dataflow_0_axi_mcdma_0:
                ip_name: axi_mcdma
            dcmac_and_gt_dcmac_0_core:
                ip_name: dcmac
